.gitignore, components/bidi/src/explicit.rs, components/bidi/src/implicit.rs, components/bidi/src/prepare.rs, components/bidi/src/process.rs, components/bidi/tests/conformance_tests.rs, components/idna/src/process.rs, components/idna/tests/conformance_tests.rs, components/normal/tests/conformance_tests.rs, components/ucd/normal/src/decomposition_type.rs
This PR is the format changes suggested by the latest release of rustfmt (`rustfmt-nightly:0.1.9`).
This is a suggestion to update to that style, rather than that of the old Syntex-based rustfmt (`rusftmt:0.9.0`) which has been discontinued due to Syntex's being discontinued, in favor of using libsyntax.
Original text below.
<hr />
Because this is a monorepo with multiple Cargo.toml, `cargo +nightly fmt` doesn't format sub-crates. (If there is functionality to do so, I haven't found it, and it should likely be added.)
In order to format a subcrate you must `cd` to the directory which contains the Cargo.toml describing the crate you are working on and then run rustfmt.
In order to keep code formatted well it must first be formatted well. I don't take hitting myself with the `git blame` on …
=> cargo fmt --all

components/bidi/Cargo.toml, components/normal/Cargo.toml, components/ucd/age/Cargo.toml
A simple bookkeeping change.
No version bumps were made. No code or API was changed, just the explicit dependency chain.
=> Move test dependencies into [dev-dependencies]

README.md, components/bidi/src/bidi_info.rs, components/bidi/src/explicit.rs, components/bidi/src/implicit.rs, components/bidi/src/level.rs, components/bidi/src/lib.rs, components/bidi/src/prepare.rs, components/bidi/tests/conformance_tests.rs, components/idna/src/process.rs, components/ucd/age/src/age.rs, components/ucd/bidi/src/bidi_class.rs, components/ucd/bidi/src/lib.rs, components/ucd/bidi/src/traits.rs, components/ucd/category/src/category.rs, components/ucd/tests/category_tests.rs, examples/ucd_bidi_traits_example.rs, src/lib.rs, tests/basics_test.rs
Update the rest of code-base to use the new enum variant names and
aliases.
Closes <https://github.com/behnam/rust-unic/issues/37>
=> Create bidi_class::abbr_names and use long names in BidiClass

.gitignore, Cargo.toml, components/bidi/Cargo.toml, components/idna/Cargo.toml, components/normal/Cargo.toml, components/ucd/Cargo.toml, components/ucd/age/Cargo.toml, components/ucd/bidi/Cargo.toml, components/ucd/category/Cargo.toml, components/ucd/core/Cargo.toml, components/ucd/normal/Cargo.toml, components/ucd/utils/Cargo.toml
Should close #34 
I'm not exactly certain how to reproduce a "download from Crates.io" locally to see if the package A) builds and B) tests successfully, but looking at the output of `cargo package --allow-dirty --list` looks optimistic.
The benefit of closing #34 will be to remove the `data/` directory from the root crate (currently ~21MiB) and allowing the subcrates to pass their tests locally without being in this repository layout.
If someone can test to make sure that those two things are true of the package, then this should be good to merge.
=> [Cargo] Exclude tools, data and data-dependent tests/benches in packages

unic/Cargo.toml, unic/ucd/Cargo.toml, unic/ucd/age/Cargo.toml, unic/ucd/age/tests/age_tests.rs, unic/ucd/normal/tests/conformance_tests.rs, unic/ucd/tests/category_tests.rs, unic/utils/Cargo.toml, unic/utils/codepoints/Cargo.toml, unic/utils/codepoints/src/codepoints.rs, unic/utils/codepoints/src/lib.rs, unic/utils/src/lib.rs
Create `unic-utils` component and put the Code Point-related utilities
under a new component named `unic-utils-codepoints`.
=> Move unic-ucd-utils to unic-utils-codepoints

.travis.yml
This will increase the time waiting for CI tests to pass, but we care
about the nightly test to pass and features depending on nightly to be
stable. So, better just drop `allow_failures`.
=> [travis] Drop allow_failures for nightly

unic/ucd/category/src/category.rs
While I was working on #43 I found this typo which was causing one of my tests to fail.
I haven't finished #43 yet but I figured I may as well fix the typo asap.
My first ever PR! :')
=> [ucd/category] Fix typo in GeneralCategory::is_symbol()

unic/ucd/category/Cargo.toml, unic/ucd/category/tests/coverage_tests.rs
The coverage test makes sure there's no overlap between major categories, except the case of `Cased_Letter` and `Letter`.
The test can catch bugs like the one fixed in <https://github.com/behnam/rust-unic/pull/60>.
=> [ucd/category] Add coverage_tests for major category methods

unic/ucd/Cargo.toml, unic/ucd/tests/category_tests.rs
This PR is my first attempt at closing #43. I have added 10 tests to the `category_tests.rs` test file.
I also corrected a typo in `category.rs` which was causing one of my tests to fail. 
Any feedback would be appreciated and I am happy to make changes.
UPDATE:
I removed my test for Bidi types OtherNeutral since from the [table of Bidi character types](http://www.unicode.org/reports/tr9/#Table_Bidirectional_Character_Types) this includes the General_Category types:
> All other characters, including OBJECT REPLACEMENT CHARACTER
Which is too general for a test - do you agree?
=> [ucd] Extend cross-component tests: GeneralCategory vs. BidiClass

unic/ucd/normal/Cargo.toml, unic/ucd/normal/tests/general_category_tests.rs
`general_category_tests` ensures the local (`normal`) implementation for
*General_Category* property returns the same result value as the
`category` component (`GeneralCategory` type), for all code points.
=> [ucd/normal] Add general_category_tests

unic/ucd/category/Cargo.toml, unic/ucd/category/src/category.rs, unic/ucd/category/tests/coverage_tests.rs
The `all_values()` static function is a new API for character
properties implemented as *flat* `enum` types in Rust, like some of
Unicode properties of type *Catalog* or *Enumeration*, to return an
exhaustive list of all possible values.
The function is useful mainly in writing integration tests, but since is
efficient in implementation, can be used in application logic, as well.
The current list is manually created and maintained. With migration to
`char_property` macros, the list will be auto-generated. (Possibly
stored in a private module and only exposed via `all_values()` API.)
See <https://github.com/behnam/rust-unic/issues/66>
=> [ucd/category] Add all_values() static fn

unic/idna/src/process.rs
The test invariants here are based on and checked against:
* Processing Step 4 of UTS#46
(<http://www.unicode.org/reports/tr46/#ProcessingStepPunycode>)
* 6.2 Decoding procedure of Punycode RFC.
(<https://ietf.org/rfc/rfc3492.txt>)
=> [idna] Add unit tests for punycode prefix edge cases

unic/utils/src/codepoints.rs, unic/utils/src/lib.rs
This PR originally proposed a more drastic change. See c061708576c5989f20820a449a05e2023ed91887. It now takes the more conservative change proposed as an alternative in the original text. See the original proposal text below.
<hr/>
This is mostly to show what the iterator would look like. Having the custom iterator comes with the benefits of having a custom iterator that implements `ExactSizeIterator` and `DoubleEndedIterator`.
Note that when `impl DoubleEndedIterator` is possible, changing `iter_all_chars` to the following gets a `DoubleEndedIterator` without a custom type:
```rust
pub fn iter_all_chars() -> impl DoubleEndedIterator<Item=char> {
(CODEPOINTS_RANGE.start..SURROGATE_RANGE.start)
.chain(SURROGATE_RANGE.end..CODEPOINTS_RANGE.end)
.map(|codepoint| { …
```
=> Return a DoubleEndedIterator from iter_all_chars

unic/ucd/age/Cargo.toml, unic/ucd/age/src/age.rs, unic/ucd/age/src/lib.rs, unic/ucd/bidi/Cargo.toml, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/bidi/src/lib.rs, unic/ucd/category/Cargo.toml, unic/ucd/category/src/category.rs, unic/ucd/category/src/lib.rs, unic/ucd/normal/Cargo.toml, unic/ucd/normal/src/canonical_combining_class.rs, unic/ucd/normal/src/composition.rs, unic/ucd/normal/src/decomposition_type.rs, unic/ucd/normal/src/gen_cat.rs, unic/ucd/normal/src/lib.rs, unic/utils/src/lib.rs, unic/utils/src/tables.rs, unic/utils/tests/table_tests.rs
This attempts to consolidate all the different places that a `bsearch_range_value_table`-like fn was defined to one canonical definition in `unic-utils`.
=> [utils] Consolidate table bsearching

unic/ucd/age/src/age.rs, unic/ucd/age/src/lib.rs, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/bidi/src/lib.rs, unic/ucd/category/Cargo.toml, unic/ucd/category/src/category.rs, unic/ucd/category/src/lib.rs, unic/ucd/core/src/lib.rs, unic/ucd/normal/src/canonical_combining_class.rs, unic/ucd/normal/src/decomposition_type.rs, unic/ucd/normal/src/lib.rs, unic/ucd/src/lib.rs, unic/utils/README.md, unic/utils/src/char_property.rs, unic/utils/src/lib.rs
Character Properties are of different kinds and shapes, and as UNIC
components grow, we need a better way to be able to categorize them by
their shape, and a way to make sure we have consistent, noncolliding
API for them.
This is the first step into building a CharProperty taxonomy, with as
little as possibly needed to provide the assurances desired.
We hope that the implementation can be improved over time with new
features added to the language. There's already some proposals in this
front. See these discussions for more details:
* [Traits as contract, without changes to call-sites](https://users.rust-lang.org/t/traits-as-contract-without-changes-to-call-sites/11938/11)
* [RFC: delegation of implementation](https://github.com/rust-lang/rfcs#1406)
=> [char_property] Implement *CharProperty traits

unic/bidi/tests/conformance_tests.rs, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/category/src/category.rs, unic/ucd/normal/src/decomposition_type.rs, unic/utils/src/char_property.rs
Add `abbr_name()` to the `EnumeratedCharProperty` contract and implement
method for UCD properties missing it.
Also, add `pub mod abbr_names` too all these properties, and add a
simple test for mapping of `abbr_names` name and `abbr_name()` value.
=> [char_property] Add EnumeratedCharProperty::abbr_name()

unic/bidi/tests/conformance_tests.rs, unic/ucd/normal/src/decomposition_type.rs, unic/utils/src/char_property.rs
See this bug report for why we need to do this at the moment: https://github.com/rust-lang/rust/issues/43777
=> [char_property] Manually enforce CompleteCharProperty inherited traits

unic/utils/src/lib.rs, unic/utils/src/macros.rs, unic/utils/tests/macro_tests.rs
Replaces #41. See #41 for earlier discussion.
An example will show better than I can tell:
```rust
char_property! {
/// Represents the Unicode character
/// [*Bidi_Class*](http://www.unicode.org/reports/tr44/#Bidi_Class) property,
/// also known as the *bidirectional character type*.
///
/// * <http://www.unicode.org/reports/tr9/#Bidirectional_Character_Types>
/// * <http://www.unicode.org/reports/tr44/#Bidi_Class_Values>
pub enum BidiClass {
/// Any strong left-to-right character
///
/// ***General Scope***
///
/// LRM, most alphabetic, syllabic, Han ideographs,
/// non-European or non-Arabic digits, ...
LeftToRight {
abbr => L,
long => Left_To_Right,
display => "Left-to-Right",
}
/// Any strong right-to-left (non-Arabic-type) character
///
/// ***General Scope***
///
/// RLM, Hebrew …
```
=> Char property macro 2.0

unic/utils/src/macros.rs, unic/utils/tests/macro_tests.rs
[`std::ascii::AsciiExt::eq_ignore_asci_case`](https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html#tymethod.eq_ignore_ascii_case)
We still check for simple equality first, so simple equality should still be fast.
=> [utils] Make char_property FromStr impl ascii case insensitive

unic/ucd/normal/src/gen_cat.rs
`.find()` is ambiguous here. `[(char, char)]` (intended) and `for<V> [(char, V)]` both match.
=> Fix ucd-normal without ucd-category

unic/ucd/Cargo.toml, unic/ucd/normal/Cargo.toml, unic/ucd/normal/src/gen_cat.rs
Basically, the dev dep record has been auto-enabling the optional dev
record for all test builds, resulting in the error to not surface.
Fix for the error surfacing by this change is
<https://github.com/behnam/rust-unic/pull/104>.
The original issue, which is (IMHO) unexpected Cargo behavior is filed
here: <https://github.com/rust-lang/cargo/issues/4395>
=> [ucd/normal] Add use-ucd-category feature

unic/ucd/Cargo.toml, unic/ucd/normal/Cargo.toml, unic/ucd/normal/src/gen_cat.rs, unic/ucd/normal/tests/general_category_tests.rs
Revert of <https://github.com/behnam/rust-unic/pull/105>
Also, add a `![cfg()]` to the integration test, to only perform it when
it matters. Also, this way, we can see if the feature is auto-enabled or
not. (Which is not!)
=> [ucd/normal] Drop use-ucd-category feature

unic/Cargo.toml, unic/idna/Cargo.toml, unic/normal/Cargo.toml
`ucd-normal` has the option to use `ucd-category`. Therefore, it makes
sense to enable the feature whenever we know `ucd-category` is
available, which include `unic` proper.
In a larger scope, I'm not sure if we want to go down this path, and may
actually worth it if we just drop the optional feature and always do
that. But, in another hand, it's a good excercise for optional
cross-component dependencies and we can decide later depending on what
other kinds of options we add.
=> [idna][normal] Add use-ucd-category feature

unic/char/Cargo.toml, unic/char/range/Cargo.toml, unic/char/range/benches/benchmarks.rs, unic/char/range/src/iter.rs, unic/char/range/src/lib.rs, unic/char/range/src/macros.rs, unic/char/range/src/range.rs, unic/char/range/src/step.rs, unic/char/range/tests/iter_tests.rs
The first half of adressing #91.
Closes #111, this manner of attack is better than it.
This PR only has one type, `CharRange`. It is effectively `std::ops::RangeInclusive` translated to characters. The matter of construction is handled by both half-open and closed constructors offered and a macro to allow for `'a'..='z'` syntax.
=> [char/range] Add CharRange and CharIter

unic/char/property/Cargo.toml, unic/char/property/src/domain.rs, unic/char/property/src/lib.rs, unic/char/property/src/macros.rs, unic/char/property/src/range.rs, unic/char/property/tests/macro_tests.rs, unic/src/lib.rs, unic/ucd/age/src/age.rs, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/category/src/category.rs, unic/ucd/normal/src/canonical_combining_class.rs, unic/ucd/normal/src/decomposition_type.rs
Add `CharProperty` trait as the core main contract for Character
Property definition, which in return requires defining the domain in
which the property is defined.
We should expand `char_property!` macro to accept these values and
implement the trait internally.
Also, we can see if we want to also enforce choosing a range for the
property. At this moment, `Age` yet doesn't have a contract trait.
=> [char/property] Add CharProperty trait

unic/char/property/src/macros.rs, unic/char/property/src/property.rs, unic/char/property/src/range_types.rs, unic/char/property/tests/macro_tests.rs, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/category/src/category.rs, unic/ucd/normal/src/decomposition_type.rs, unic/ucd/normal/tests/excluded_composition_tests.rs
Add `long_name(&self)`/`human_name(&self)` to the
`EnumeratedCharProperty` contract and add values to the implementing
types.
Also needs to be implemented by `char_property!` macro.
These name methods *may* not belong to *Enumerated* contract, but this
is the only contract we have right now that provides them, so let's
start with having them here.
Bascially, looks like we have to major categories of property range
types: those with pre-defined set of possible values (*Enumerated*, and
possibly other ones), and those with numeric/complex values, which don't
have *named* variants for all of them, which would result in
name-generation to be runtime and not compile time.
For the second group, we can add another parent contract to implement
these methods as `fn *_name(&self) -> String`, which …
=> [char/property] Add long_name()/human_name() to EnumeratedCharProperty

unic/bidi/Cargo.toml, unic/bidi/tests/conformance_tests.rs, unic/char/property/src/macros.rs, unic/char/property/tests/macro_tests.rs, unic/ucd/bidi/src/bidi_class.rs, unic/ucd/bidi/src/lib.rs, unic/ucd/category/src/category.rs, unic/ucd/category/src/lib.rs, unic/ucd/category/tests/major_category_tests.rs, unic/ucd/normal/src/composition.rs, unic/ucd/normal/src/decomposition_type.rs, unic/ucd/normal/src/lib.rs, unic/ucd/normal/tests/conformance_tests.rs
I can submit a separate PR after 31e6582 if we want to pull the edited macro and the application separately.
The diff is kind of opaque because this touches so much. You're probably better off just comparing before/after the PR without looking at the diff output.
This PR is submitted in a ready-to-merge (after review) state rather than my more usual track-final-polish.
This will require a rebase of #118 as it touches many of the same parts of the code.
=> [char/property] [ucd] Macro update and use

unic/ucd/bidi/src/bidi_class.rs, unic/ucd/category/src/category.rs, unic/ucd/normal/src/canonical_combining_class.rs, unic/ucd/normal/src/composition.rs, unic/ucd/normal/src/decomposition_type.rs, unic/ucd/normal/src/gen_cat.rs
the `use ...::*` is considered a bad practice and should be avoided as
much as possible, or limited to the scope where it's needed.
A major case we have needed them in UCD components is when loading data
from `rsv` files, where we don't want to prefix values in every single
line with the type name. To limit the scope of the wildcard usage, I
have moved these to a local `mod data`.
=> [ucd] Drop `use ...::*` lines outside of data or tests

.gitattributes
GitHub thinks the repository is 53.7% RenderScript and 45.5% Rust. Oops!
This just tells GitHub/linguist to ignore any files matching `**/tables/*` as generated code.
Another option is the following .gitattributes:
```gitattributes
*.rs linguist-language=Rust
*.rsv linguist-generated=true
```
<https://github.com/github/linguist#troubleshooting>
=> GitHub: Ignore generated files

unic/tests/unicode_version_tests.rs, unic/ucd/core/src/lib.rs
Also, add TODO items for adding convertors to/from internal
`UnicodeVersion` type.
=> [unicode_version_tests] Re-enable std::char comparison

.travis.yml, unic/ucd/normal/src/hangul.rs, unic/ucd/normal/tests/general_category_tests.rs
Replace `mem::transmute()` with `char::from_u32_unchecked()`, as its
more clear on the semantics.
Also fix a broken integration test which is only run in special
conditions.
[travis] Add test step for unic-ucd-normal
=> [ucd/normal/hangul] Use from_u32_unchecked

unic/char/property/src/property.rs, unic/ucd/age/src/age.rs, unic/ucd/core/src/lib.rs, unic/ucd/name/src/name.rs, unic/ucd/normal/src/canonical_combining_class.rs
The former implementation adds an unnecessary allocation to the `Display` impl. Because implementing `Display` gives the `to_string` method for free, there shouldn't be any `Display` methods.
If there are any methods which offer strings that differ from the `Display` implementation, those should have different names. I deprecated the methods instead of removing them, just to be safe.
=> Replace unnecessary display methods with to_string.

.travis.yml, Cargo.toml, apps/cli/Cargo.toml, apps/cli/README.md, apps/cli/src/bin/unic-echo.rs, apps/cli/src/bin/unic-inspector.rs, apps/cli/src/clap_macros.rs, apps/cli/src/lib.rs, apps/cli/src/parsers.rs, apps/cli/src/writers.rs, apps/cli/tests/quickcheck.rs, apps/cli/tests/test_unic-echo.rs
`unic-cli` package provides comman-line tools for developers, helping
with common Unicode tasks, like generating, inspecting, and transforming
strings.
`unic-echo` is a command-line tool, similar to the common `echo`
command, producing Unicode strings, with support for common escaping
forms for input and output.
`unic-inspector` is a command-line tool to inspect Unicode strings
per-character.
=> [apps] Add unic-cli package, unic-echo binary

README.md, apps/cli/Cargo.toml, etc/common.sh, etc/publish-all.sh, gen/Cargo.toml, unic/Cargo.toml, unic/bidi/Cargo.toml, unic/char/Cargo.toml, unic/char/property/Cargo.toml, unic/char/range/Cargo.toml, unic/common/Cargo.toml, unic/emoji/Cargo.toml, unic/emoji/char/Cargo.toml, unic/idna/Cargo.toml, unic/idna/mapping/Cargo.toml, unic/idna/punycode/Cargo.toml, unic/normal/Cargo.toml, unic/segment/Cargo.toml, unic/ucd/Cargo.toml, unic/ucd/age/Cargo.toml, unic/ucd/bidi/Cargo.toml, unic/ucd/case/Cargo.toml, unic/ucd/category/Cargo.toml, unic/ucd/common/Cargo.toml, unic/ucd/ident/Cargo.toml, unic/ucd/name/Cargo.toml, unic/ucd/normal/Cargo.toml, unic/ucd/segment/Cargo.toml, unic/ucd/version/Cargo.toml
UNIC Applications are binary creates hosting in the same repository as `unic` super-crate, under the `apps/` directory. These creates are not internal parts of the `unic` library, but tools designed and developed for the general audience, also serving as a test bed for the UNIC API. We are starting with CLI applications, and possibly expanding it to GUI and WEB applications, as well.
- [`unic-cli`] The new UNIC CLI application provides command-line tools for working with Unicode characters and strings. In this release, first versions of `unic-echo` and `unic-inspector` commands are implemented.
- [`unic-ucd-common `] Common character properties (*alphabetic*, *alphanumeric*, *control*, *numeric*, and *white_space*).
- [`unic-ucd-ident`] Unicode Identifier character properties.
- …
=> Release v0.7.0

unic/tests/char_range_integration_tests.rs, unic/ucd/Cargo.toml, unic/ucd/case/Cargo.toml, unic/ucd/examples/lowercase_chars_with_identity_touppercase.rs, unic/ucd/examples/uppercase_chars_with_identity_tolowercase.rs
Add example code for comparing Case properties with `General_Category`:
- `lowercase_chars_with_identity_touppercase`
- `uppercase_chars_with_identity_tolowercase`
=> [ucd] Add examples

apps/cli/src/bin/unic-echo.rs, etc/check-components.sh, etc/common.sh, etc/format.sh, unic/char/range/src/range.rs, unic/ucd/README.md, unic/ucd/common/src/lib.rs, unic/ucd/src/lib.rs
Update `format.sh` to use `nightly` version of `rustfmt` for formatting,
as some features we use have not yet madde it to the `stable` release.
And format the files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-i18n/rust-unic/244)
=> etc: Update components list and some clean-up

unic/ucd/ident/src/lib.rs
This is a them as https://github.com/open-i18n/rust-unic/pull/253, but fixing the missing underscore in the new table file name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-i18n/rust-unic/255)
=> ucd/ident: Use correct data table for white_space
